server:
  port: 8989

#Database Setup - PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtdemodb1?currentSchema=jwtschema1
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

